name: daily_achievements
description: "每日成就"
publish_to: "none"
version: 1.0.0+0.1.3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  image_picker: ^1.1.2
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background@3x.png
    - assets/images/butter_Square@3x.png
    - assets/images/img_avatar@3x.png
    - assets/images/flag.png
